version: '1'

services:
  app:
    container_name: rest-server-go
    build:
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: rest-server-go-postgresql
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    container_name: rest-server-go-redis
    build:
      context: ./docker/redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  

